### ISSUE TITLE
Default snapserver user does not have permissions to .json file

### ISSUE THREAD

**Issue by KraigoMpls** [badaix/snapcast#534] opened 2020-01-28 00:15 UTC
On a Raspberry Pi with a Buster image, v 15 of SnapServer works fine as a service.  When I upgrade to v 18 SnapServer fails to start.  The debug log lists:

[Error] (main) Exception: failed to open file "/var/lib/snapserver/server.json", permission denied (error 13)

It appears that user and group _snapserver from v15 have permissions to the file but user and group snapserver from v18 do not.

I apologize if I am not clear with this.  Thank you for your time.

KO

**Comment by KraigoMpls** [comment] 2020-01-28 01:08
I didn't want to be this ham handed about it, but "sudo chown snapserver: /var/lib/snapserver/server.json" got things to work.

KO

**Comment by badaix** [comment] 2020-01-28 07:15
I think the user `_snapserver` was introduced in v0.16, not 0.15, and changed back to `snapserver` in v0.17. 
This seems to be a duplicate of #505

**Closed by badaix** 2020-01-28 07:15 UTC

**Comment by KraigoMpls** [comment] 2020-01-28 12:04
Thanks for your patient reply.  I didn't touch 0.16 or 0.17.  It was definitely in 0.15.

**Comment by badaix** [comment] 2020-01-28 12:46
Did you install the APK from the releases page or maybe an official debian package? 
I've copy/pasted the underscore usernames from the debian build scripts, so there they exist for a longer time, also in v0.15
