### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by PureTryOut** [badaix/snapcast#67] opened 2016-05-29 09:13 UTC
I'm interested in trying this, however my music streaming server runs FreeBSD (10.3). Is there any chance for FreeBSD support and a list of dependencies it requires on there?

**Comment by ioangogo** [comment] 2016-05-31 14:14
To help aid this, maybe leaving alsa for oss or providing a way for the user to configure a audio back end that this program uses rather than forcing alsa(This will aid in a windows port) to be the backend.

**Comment by 1337sup3rh4x0r** [comment] 2016-06-19 20:30
does the snapserver even require an audio backend or could the server run on FreeBSD already with no changes?

**Comment by ioangogo** [comment] 2016-06-19 20:32
Not really, but using standard ones allows you to work syncronised the delay caused by them

**Comment by ioangogo** [comment] 2016-06-19 20:34
I like the idea of having config options for different with backends with the delay accounted for

**Comment by badaix** [comment] 2016-06-26 11:25
The Snapserver in the [develop branch](https://github.com/badaix/snapcast/tree/develop) can now be compiled under FreeBSD. To build it, you can follow the [guide](https://github.com/badaix/snapcast/blob/develop/doc/build.md#freebsd-native).
There is currently no install option for FreeBSD (BSD-style init), but only the plain binary: [snapserver.zip](https://github.com/badaix/snapcast/files/333540/snapserver.zip)

**Comment by PureTryOut** [comment] 2016-06-28 13:10
Thanks! I'll try it soon and report back.

**Comment by PureTryOut** [comment] 2016-06-28 16:43
Got the following error while compiling (all dependencies installed):
```
/usr/local/bin/g++ -std=c++0x -Wall -Wno-unused-function -O3 -pthread -DASIO_STANDALONE -DVERSION=\"0.7.0\" -I. -I.. -I../externals/asio/asio/include -I../externals/popl/include -DNO_CPP11_STRING -DFREEBSD -c snapServer.cpp -o snapServer.o
snapServer.cpp:23:20: fatal error: popl.hpp: No such file or directory
 #include "popl.hpp"
                    ^
compilation terminated.
Makefile:47: recipe for target 'snapServer.o' failed
gmake: *** [snapServer.o] Error 1
```

**Comment by badaix** [comment] 2016-06-28 17:20
did you clone the externals?

    $ cd <snapcast dir>/externals
    $ git submodule update --init --recursive

**Comment by PureTryOut** [comment] 2016-06-28 19:53
I'll be honest: I did not. It builds fine now. I can't really find that in the documentation anywhere, could it be added?

**Comment by badaix** [comment] 2016-06-28 20:11
It's written on top of the [build-snapcast guid](https://github.com/badaix/snapcast/blob/master/doc/build.md#build-snapcast)

**Comment by PureTryOut** [comment] 2016-06-28 20:11
Aah that's just me being blind then, thanks.

**Comment by PureTryOut** [comment] 2016-06-28 20:17
`sudo gmake install` complains about /bin/bash missing, this is true since it's in `/usr/local/bin/bash` instead.
After changing it manually in the Makefile, it complains with `install: target directory '/usr/sbin/snapserver' does not exist`.
After creating this directory manually it complains with `install: root: No such file or directory`.

I'm sorry for bothering you with this all, but we're close now!

**Comment by badaix** [comment] 2016-06-28 20:27
This is what I meant by:
> There is currently no install option for FreeBSD (BSD-style init), but only the plain binary

I just took care about compiling the server so far. I don't know yet how the BSD-style init works.
It should already be possible to start the Snapserver manually.

**Comment by PureTryOut** [comment] 2016-06-28 20:29
Aah no problem, thanks for all your help so far.

**Comment by PureTryOut** [comment] 2016-06-28 21:39
[I made a quick and dirty init script](https://gist.github.com/PureTryOut/bafa9d0deeac35b5fc9d752aa96f6225). It's my first init script for FreeBSD: there are probably things wrong or things that could be done better. Shamelesly copied from the MusicPD port.

The binary is assumed to be `/usr/local/bin/snapserver` and the default config file `/usr/local/etc/snapcast.conf` (however nothing is done with the config file right now).

**Comment by badaix** [comment] 2016-06-29 07:15
Nice! I will integrate this into the project :smiley: 
I think the `REQUIRE` field is more about required services, as e.g. Network is up

**Comment by PureTryOut** [comment] 2016-06-29 07:40
That makes more sense really. I'll look into it when I'm back home.

**Comment by badaix** [comment] 2016-07-02 11:39
I've added the rc script now to the develop branch. Also `gmake TARGET=FREEBSD install` should now work (see the updated [guide](https://github.com/badaix/snapcast/blob/develop/doc/build.md))

**Comment by PureTryOut** [comment] 2016-07-02 18:45
Cool, it works great, thanks! In the guide btw, it says that the startup script is installed to `/local/etc/rc.d/snapserver`, which should of course be `/usr/local/etc/rc.d/snapserver`. Also maybe it should be made clear that the `snapserver_opts="your custom options"` can be set in `/usr/local/etc/rc.d/snapserver`. It prevents people from having to search where to add it (knowning me ;)).

**Comment by badaix** [comment] 2016-07-03 09:54
thanks, done: 9ef4c690356e20d0bd376bd189b14c05a14e7426.
I changed the options thing to:

> For additional command line arguments, add in `/etc/rc.conf`:
  		  
      snapserver_opts="<your custom options>"

I think it's better style to not touch the rc script, but to change the `snapserver_opts` variable in the `rc.conf`. But I might be wrong. I'm not familiar with FreeBSD and the do's and don'ts.

**Comment by PureTryOut** [comment] 2016-07-03 10:21
Yeah I guess so, you're not really meant to change init scripts as an user.

Anyways it seems to run fine now, although it spits some errors when launching:
```
Starting snapserver.
Settings file: //.config/snapcast/server.json
lsb_release: not found
cat: /etc/os-release: No such file or directory
cat: /etc/openwrt_release: No such file or directory
arch: not found
lsb_release: not found
cat: /etc/os-release: No such file or directory
cat: /etc/openwrt_release: No such file or directory
arch: not found
lsb_release: not found
cat: /etc/os-release: No such file or directory
cat: /etc/openwrt_release: No such file or directory
arch: not found
lsb_release: not found
cat: /etc/os-release: No such file or directory
cat: /etc/openwrt_release: No such file or directory
arch: not found
```

They're not really important I guess, but it would be nice to have them gone.

**Comment by badaix** [comment] 2016-07-03 19:52
this should be fixed now in [develop branch](https://github.com/badaix/snapcast/tree/develop).
Please update :smiley:

**Comment by PureTryOut** [comment] 2016-07-06 17:12
Thanks! Everyone seems to be fixed and working properly now! Now we just have to wait till a FreeBSD developer adds it to the ports tree :smile:

**Closed** 2016-07-09 10:04 UTC
