### ISSUE TITLE
changing server via the API

### ISSUE THREAD

**Issue by fcorthay** [badaix/snapcast#1250] opened 2024-06-19 09:39 UTC
I would like to have a snapclient change snapserver via the JSON API. This would e.g. allow to programmatically select either the central home music or a local room's one. The two (or more) servers are running on different machines.

For the moment, the API allows to get a client's status and change its `config` parameters such as the volume. With a request such as `Client.SetConnected`, one could disconnect a client from a given server and connect it to another one.

For the time being, I can modifiy `/etc/default/snapclient` and restart the snapclient service. Yet this implies to give a user sudo privilieges such as the ability to restart the service.

**Comment by badaix** [comment] 2024-06-19 14:39
Duplicate of #758

**Closed by badaix** 2024-06-19 14:39 UTC
Labels: wontfix, feature request
