### ISSUE TITLE
Android 6 nulls out mac addresses

### ISSUE THREAD

**Issue by Kernald** [badaix/snapcast#246] opened 2017-05-29 19:11 UTC
Starting with Android 6, there's no SDK-supported way to get the hardware mac address: https://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-hardware-id

As a result, having different Android 6+ clients on the same server, they end up mixed up. I had a client A (running Android 7) in a group 1, a client B (also running Android 7) in a group 2, when B started up and connected itself to the snapcast server, it was identified as A, hence didn't have the sound of group 2, but group 1.

**Comment by badaix** [comment] 2017-05-30 12:50
Is it shown as `02:00:00:00:00:00`?
Snapcast doesn't use the SDK, but native C++ code to get the interface's MAC address.

**Comment by Kernald** [comment] 2017-05-30 12:53
It's shown as `00:00:00:00:00:00`. I attached a screenshot of the details screen.
![screenshot_20170530-145134](https://cloud.githubusercontent.com/assets/296840/26584013/9d05e8e0-4547-11e7-8494-86504996bb14.png)

**Comment by badaix** [comment] 2017-06-01 09:15
Weird, I will try to reproduce it with an emulator.
What's needed is not necessarily the MAC address, but a unique ID. It seems to be difficult to get a unique host ID in Android. It should be possible (but not straight forward) to get a device ID via the SDK (as [here](https://stackoverflow.com/questions/2785485/is-there-a-unique-android-device-id)), but using the NDK, a `getprop ro.serialno` might work. I have to check in more detail...
Maybe the App could use the SDK to get an ID and pass it to the snapclient binary.

**Comment by Kernald** [comment] 2017-06-01 09:27
If you want me to try a specific branch or something like that, feel free to ask, I'll be happy to help :-)

For reference, the issue appears on both a Sony Xperia X Compact and an nVidia Shield TV. I'm pretty sure I noticed it on an nVidia Shield Tablet K1 too, but it's currently in a moving box, I can't check right now. Anyway, Android 7 seems to be the only common denominator between the Shield TV and the X Compact.

**Comment by badaix** [comment] 2017-06-07 10:08
the develop branch uses a fallback to `getprop ro.serialno` 5bf78eb87468b2dd56f9bf96477c3ccd6690df3a
Maybe there is more come with issue #249

**Comment by Kernald** [comment] 2017-06-08 13:07
Sadly I can't build libFLAC on my Mac (I don't really understand why, `ranlib` is failing, the build then ends up in undefined references) and I don't have access to a Linux box right now. If you don't have an Android 6+ device, I'll be glad to test if you can make an APK available somewhere.

**Comment by badaix** [comment] 2017-06-10 18:09
Here it is: [Snapcast_0.11.90.apk.zip](https://github.com/badaix/snapcast/files/1066025/Snapcast_0.11.90.apk.zip)
It's compatible to Snapserver 0.11, but you have to use a recent develop version for the unique host Id to work properly. Can you compile the server?

**Comment by Kernald** [comment] 2017-06-10 19:30
Thanks for the build. I can compile the server, it's much easier when Android's NDK is out of the way :-)

And it seems to be working perfectly on Android 7:

![screenshot_20170610-212655](https://user-images.githubusercontent.com/296840/27005689-c8fdec2e-4e23-11e7-8b48-a9c5be5fcea7.png)

Thanks a lot, that was quick!

**Comment by badaix** [comment] 2017-10-17 19:42
Fixed in version [v0.12.0](https://github.com/badaix/snapcast/releases/tag/v0.12.0)

**Closed by badaix** 2017-10-17 19:42 UTC

**Comment by lettore** [comment] 2019-07-21 10:28
I'm facing the same problem with android Oreo 8.1.0 all my devices are seen as one. MAC address 00:00:00:00:00:00
