### ISSUE TITLE
snapclient: allow setting the client name and group to join from the command line

### ISSUE THREAD

**Issue by rmalchow** [badaix/snapcast#759] opened 2021-01-03 09:44 UTC
it would be great to have some more control over the naming from both snapserver command line ("default group for new clients") and snapclient ("client name" and optional "group to join"). the stretch goal would be to use the hostname (if you want to guarantee uniqueness, with a random extension (e.g. "music-pi-FC4D"). i think this would be nicer than having clients show up with entirely cryptic names. 

on the other hand, at least the client name might be a purely UI kind of issue - with the snapcast integration in iris, i can actually see the hostnames as well.

**Comment by badaix** [comment] 2021-02-19 10:06
The hostname _is_ already used. I don't know what cryptic names you're talking about.

**Comment by badaix** [comment] 2021-02-19 17:35
Duplicate of #308 and #515

**Closed by badaix** 2021-02-19 17:35 UTC
Labels: feature request
