### ISSUE TITLE
Snapclient hangs after changing stream

### ISSUE THREAD

**Issue by sgoudsme** [badaix/snapcast#564] opened 2020-03-16 18:55 UTC
Hi,

I have your multiroom audio running with 4 clients and 4 streams. Two are Librespot streams, the other two are connected to a pipe with MPD. I control everything via Home Assistant. 
I noticed in version v0.19.0 when I change between channels, the snapclient stops working. There is no possibility to change to another stream. The only way to get audio again is by killing the process and start it again.
I installed Snapserver v0.19.0 on Ubuntu 18.04.4. I created a Docker container for the Snapclient.
The Console output is shown beneath. you can see that I switch two channels. In the end, it hangs at the message: `[Info] (onMessageReceived) Codec: flac`. 
The software hanging is random: Sometimes I can change stream more than 10 times, now it was after changing 4 times.
I tested this behaviour at v0.18.0 (also in Docker) and had no problems.
The Docker container can be found at [sgoudsme/snapclient](https://hub.docker.com/layers/sgoudsme/snapclient/0.19.0/images/sha256-82443e052987d6dbfa5b7489cc47d24352406b39a2e5ad23cad49e120511e123?context=repo).

> audio_dinner  | 2020-03-16 18-40-56 [Info] (main) Latency: 0
> audio_dinner  | 2020-03-16 18-40-56 [Notice] (start) Connected to 192.168.1.100
> audio_dinner  | 2020-03-16 18-40-56 [Info] (getMacAddress) My MAC: "02:42:ac:1e:00:02", socket: 6
> audio_dinner  | metadata:{"STREAM":"Sibrecht"}
> audio_dinner  | 2020-03-16 18-40-56 [Info] (onMessageReceived) ServerSettings - buffer: 1000, latency: 0, volume: 27, muted: 0
> audio_dinner  | 2020-03-16 18-40-56 [Info] (onMessageReceived) Codec: flac
> audio_dinner  | 2020-03-16 18-40-56 [Notice] (state) sampleformat: 44100:16:2
> audio_dinner  | 2020-03-16 18-40-56 [Info] (Alsa) frames: 940
> audio_dinner  | 2020-03-16 18-40-56 [Info] (Alsa) Resizing buffer from 0 to 15052
> audio_dinner  | 2020-03-16 18-40-56 [Info] (Stream) no chunks available
> audio_dinner  | 2020-03-16 18-40-56 [Info] (Alsa) Failed to get chunk
> audio_dinner  | 2020-03-16 18-40-56 [Info] (worker) diff to server [ms]: 0.006
> audio_dinner  | 2020-03-16 18-40-57 [Info] (Stream) Chunk: 0	0	0	0	1	64	0
> audio_dinner  | 2020-03-16 18-40-58 [Info] (Stream) Chunk: 7	6	4	4	42	63	0
> audio_dinner  | 2020-03-16 18-40-59 [Info] (Stream) Chunk: 16	14	8	8	89	64	0
> audio_dinner  | 2020-03-16 18-40-59 [Info] (onMessageReceived) Codec: flac
> audio_dinner  | metadata:{"STREAM":"Stil"}
> audio_dinner  | 2020-03-16 18-40-59 [Notice] (state) sampleformat: 48000:16:2
> audio_dinner  | 2020-03-16 18-40-59 [Inf[Info] (onMessageReceived) Codec: flaco] (Alsa) frames: 1024
> audio_dinner  | 2020-03-16 18-40-59 [Info] (Alsa) Resizing buffer from 0 to 16384
> audio_dinner  | 2020-03-16 18-40-59 [Info] (Stream) no chunks available
> audio_dinner  | 2020-03-16 18-40-59 [Info] (Alsa) Failed to get chunk
> audio_dinner  | 2020-03-16 18-41-02 [Info] (onMessageReceived) Codec: flac
> audio_dinner  | metadata:{"STREAM":"Sibrecht"}
> audio_dinner  | 2020-03-16 18-41-02 [Notice] (state) sampleformat: 44100:16:2
> audio_dinner  | 2020-03-16 18-41-02 [Info] (Alsa) frames: 940
> audio_dinner  | 2020-03-16 18-41-02 [Info] (Alsa) Resizing buffer from 0 to 15052
> audio_dinner  | 2020-03-16 18-41-03 [Info] (Stream) Chunk: 0	0	0	0	1	64	0
> audio_dinner  | 2020-03-16 18-41-04 [Info] (Stream) Chunk: 7	6	4	4	42	63	0
> audio_dinner  | 2020-03-16 18-41-05 [Info] (Stream) Chunk: 16	14	8	8	89	64	0
> audio_dinner  | metadata:{"STREAM":"Stil"}
> audio_dinner  | 2020-03-16 18-41-05 [Info] (onMessageReceived) Codec: flac

**Comment by badaix** [comment] 2020-03-16 19:26
I switched 30 times forth and back (between Librespot 44100:16:2 and MPD 48000:16:2) without any problem. Please try with with a plain Snapcast installation. Also you can activate more logging with `--debug` on command line.

**Comment by sgoudsme** [comment] 2020-03-16 19:50
I had it now after switching just one time. 
I will try it with plain installation maybe tomorrow.
Tested it again with the `--debug option` (I don't think you will get any wiser...):
```
audio_dinner  | 2020-03-16 19-47-42.237 [Info] (main) Latency: 0
audio_dinner  | 2020-03-16 19-47-42.238 [Debug] (start) Connecting
audio_dinner  | 2020-03-16 19-47-42.240 [Notice] (start) Connected to 192.168.1.100
audio_dinner  | 2020-03-16 19-47-42.240 [Info] (getMacAddress) My MAC: "02:42:c0:a8:c0:02", socket: 6
audio_dinner  | 2020-03-16 19-47-42.254 [Info] (onMessageReceived) ServerSettings - buffer: 1000, latency: 0, volume: 13, muted: 0
audio_dinner  | 2020-03-16 19-47-42.254 [Info] (onMessageReceived) Codec: flac
audio_dinner  | 2020-03-16 19-47-42.254 [Notice] (state) sampleformat: 44100:16:2
audio_dinner  | 2020-03-16 19-47-42.254 [Debug] (setVolume_exp) setVolume exp: 0.13 => 0.0387737
audio_dinner  | metadata:{"STREAM":"Sibrecht"}
audio_dinner  | 2020-03-16 19-47-42.265 [Debug] (Alsa) PCM name: default:CARD=Set
audio_dinner  | 2020-03-16 19-47-42.265 [Debug] (Alsa) PCM state: PREPARED
audio_dinner  | 2020-03-16 19-47-42.265 [Debug] (Alsa) channels: 2
audio_dinner  | 2020-03-16 19-47-42.265 [Debug] (Alsa) rate: 44100 bps
audio_dinner  | 2020-03-16 19-47-42.265 [Info] (Alsa) frames: 940
audio_dinner  | 2020-03-16 19-47-42.265 [Debug] (Alsa) period time: 21333
audio_dinner  | 2020-03-16 19-47-42.266 [Info] (Alsa) Resizing buffer from 0 to 15052
audio_dinner  | 2020-03-16 19-47-42.285 [Info] (worker) diff to server [ms]: 0.003
audio_dinner  | 2020-03-16 19-47-43.160 [Debug] (Stream) Silent frames: 769, frames: 925, age: -17.455
audio_dinner  | 2020-03-16 19-47-43.182 [Info] (Stream) Chunk: 0	0	0	0	1	63	0
audio_dinner  | 2020-03-16 19-47-43.287 [Debug] (worker) time sync main loop
audio_dinner  | 2020-03-16 19-47-44.014 [Info] (Stream) Chunk: 7	5	3	3	40	63	0
audio_dinner  | 2020-03-16 19-47-44.289 [Debug] (worker) time sync main loop
audio_dinner  | metadata:{"STREAM":"Stil"}
audio_dinner  | 2020-03-16 19-47-44.946 [Info] (onMessageReceived) Codec: flac
audio_dinner  | 2020-03-16 19-47-45.290 [Debug] (worker) time sync main loop
audio_dinner  | 2020-03-16 19-47-46.292 [Debug] (worker) time sync main loop
audio_dinner  | 2020-03-16 19-47-47.294 [Debug] (worker) time sync main loop
audio_dinner  | 2020-03-16 19-47-48.296 [Debug] (worker) time sync main loop
audio_dinner  | 2020-03-16 19-47-49.297 [Debug] (worker) time sync main loop
audio_dinner  | 2020-03-16 19-47-50.298 [Debug] (worker) time sync main loop
audio_dinner  | 2020-03-16 19-47-51.300 [Debug] (worker) time sync main loop
audio_dinner  | 2020-03-16 19-47-52.302 [Debug] (worker) time sync main loop
audio_dinner  | 2020-03-16 19-47-53.303 [Debug] (worker) time sync main loop
audio_dinner  | 2020-03-16 19-47-54.305 [Debug] (worker) time sync main loop
audio_dinner  | 2020-03-16 19-47-55.307 [Debug] (worker) time sync main loop
```

**Comment by badaix** [comment] 2020-03-16 19:57
Is it just one client that hangs or all at once?
Can you try another codec? Preferably pcm?

**Comment by sgoudsme** [comment] 2020-03-16 20:13
Only one client that hangs, the one that I wanted to change stream.
I don't know how to change codec, unless by selecting another audio card from the `-l` list.
Now I can not reproduce the error. Seems like it is working anyway... Strange that it works for the same audio card in v0.18 and not for v0.19... But it is fine for me. 
Thank you! (and thank you for making this beautiful piece of software ;) )

**Comment by badaix** [comment] 2020-03-16 20:34
you can change the codec in `snapserver.conf`:
```
# Default transport codec
# (flac|ogg|opus|pcm)[:options]
# Type codec:? to get codec specific options
#codec = flac
```
or pass the codec to your stream definition with `&codec=pcm`

**Comment by sgoudsme** [comment] 2020-03-16 20:45
Hi,
I changed the codec to pcm, but got exact the same behaviour:

> audio_dinner  | 2020-03-16 20-43-04.216 [Info] (main) Latency: 0
> audio_dinner  | 2020-03-16 20-43-04.217 [Debug] (start) Connecting
> audio_dinner  | 2020-03-16 20-43-04.217 [Notice] (start) Connected to 192.168.2.1
> audio_dinner  | 2020-03-16 20-43-04.217 [Info] (getMacAddress) My MAC: "02:42:c0:a8:60:02", socket: 6
> audio_dinner  | 2020-03-16 20-43-04.227 [Info] (onMessageReceived) ServerSettings - buffer: 1000, latency: 0, volume: 13, muted: 0
> audio_dinner  | 2020-03-16 20-43-04.227 [Info] (onMessageReceived) Codec: pcm
> audio_dinner  | 2020-03-16 20-43-04.227 [Notice] (state) sampleformat: 44100:16:2
> audio_dinner  | 2020-03-16 20-43-04.228 [Debug] (setVolume_exp) setVolume exp: 0.13 => 0.0387737
> audio_dinner  | metadata:{"STREAM":"Sibrecht"}
> audio_dinner  | 2020-03-16 20-43-04.237 [Debug] (Alsa) PCM name: default:CARD=Set
> audio_dinner  | 2020-03-16 20-43-04.237 [Debug] (Alsa) PCM state: PREPARED
> audio_dinner  | 2020-03-16 20-43-04.237 [Debug] (Alsa) channels: 2
> audio_dinner  | 2020-03-16 20-43-04.237 [Debug] (Alsa) rate: 44100 bps
> audio_dinner  | 2020-03-16 20-43-04.237 [Info] (Alsa) frames: 940
> audio_dinner  | 2020-03-16 20-43-04.237 [Debug] (Alsa) period time: 21333
> audio_dinner  | 2020-03-16 20-43-04.238 [Info] (Alsa) Resizing buffer from 0 to 15052
> audio_dinner  | 2020-03-16 20-43-04.239 [Info] (Stream) no chunks available
> audio_dinner  | 2020-03-16 20-43-04.239 [Info] (Alsa) Failed to get chunk
> audio_dinner  | 2020-03-16 20-43-04.258 [Info] (worker) diff to server [ms]: 0.005
> audio_dinner  | 2020-03-16 20-43-05.133 [Debug] (Stream) Silent frames: 893, frames: 925, age: -20.261
> audio_dinner  | 2020-03-16 20-43-05.155 [Info] (Stream) Chunk: 0	0	0	0	1	63	0
> audio_dinner  | 2020-03-16 20-43-05.259 [Debug] (worker) time sync main loop
> audio_dinner  | 2020-03-16 20-43-06.008 [Info] (Stream) Chunk: 7	6	4	4	41	64	0
> audio_dinner  | 2020-03-16 20-43-06.261 [Debug] (worker) time sync main loop
> audio_dinner  | 2020-03-16 20-43-07.012 [Info] (Stream) Chunk: 17	15	9	9	88	63	0
> audio_dinner  | 2020-03-16 20-43-07.263 [Debug] (worker) time sync main loop
> audio_dinner  | 2020-03-16 20-43-08.013 [Info] (Stream) Chunk: 22	21	16	13	135	64	-14
> audio_dinner  | 2020-03-16 20-43-08.265 [Debug] (worker) time sync main loop
> audio_dinner  | 2020-03-16 20-43-09.016 [Info] (Stream) Chunk: 25	25	21	17	182	64	-22
> audio_dinner  | 2020-03-16 20-43-09.266 [Debug] (worker) time sync main loop
> audio_dinner  | 2020-03-16 20-43-10.019 [Info] (Stream) Chunk: 29	29	25	20	229	63	-22
> audio_dinner  | 2020-03-16 20-43-10.268 [Debug] (worker) time sync main loop
> audio_dinner  | 2020-03-16 20-43-11.021 [Info] (Stream) Chunk: 32	33	29	22	276	64	-22
> audio_dinner  | 2020-03-16 20-43-11.270 [Debug] (worker) time sync main loop
> audio_dinner  | 2020-03-16 20-43-12.025 [Info] (Stream) Chunk: 36	36	33	23	323	64	-22
> audio_dinner  | 2020-03-16 20-43-12.271 [Debug] (worker) time sync main loop
> audio_dinner  | 2020-03-16 20-43-13.006 [Info] (Stream) Chunk: 41	40	37	26	369	64	-22
> audio_dinner  | 2020-03-16 20-43-13.273 [Debug] (worker) time sync main loop
> audio_dinner  | 2020-03-16 20-43-14.009 [Info] (Stream) Chunk: 44	44	40	28	416	64	-22
> audio_dinner  | 2020-03-16 20-43-14.275 [Debug] (worker) time sync main loop
> audio_dinner  | 2020-03-16 20-43-15.012 [Info] (Stream) Chunk: 47	46	44	30	463	63	-22
> audio_dinner  | 2020-03-16 20-43-15.276 [Debug] (worker) time sync main loop
> audio_dinner  | metadata:{"STREAM":"Stil"}
> audio_dinner  | 2020-03-16 20-43-15.436 [Info] (onMessageReceived) Codec: pcm
> audio_dinner  | 2020-03-16 20-43-16.278 [Debug] (worker) time sync main loop
> audio_dinner  | 2020-03-16 20-43-17.280 [Debug] (worker) time sync main loop
> audio_dinner  | 2020-03-16 20-43-18.282 [Debug] (worker) time sync main loop
> audio_dinner  | 2020-03-16 20-43-19.283 [Debug] (worker) time sync main loop
> audio_dinner  | 2020-03-16 20-43-20.284 [Debug] (worker) time sync main loop
> audio_dinner  | 2020-03-16 20-43-21.286 [Debug] (worker) time sync main loop
> audio_dinner  | 2020-03-16 20-43-22.288 [Debug] (worker) time sync main loop
> audio_dinner  | 2020-03-16 20-43-23.289 [Debug] (worker) time sync main loop
> audio_dinner  | 2020-03-16 20-43-24.291 [Debug] (worker) time sync main loop
> audio_dinner  | 2020-03-16 20-43-25.293 [Debug] (worker) time sync main loop
> audio_dinner  | 2020-03-16 20-43-26.295 [Debug] (worker) time sync main loop

**Comment by badaix** [comment] 2020-03-16 21:01
Then you're ending up somewhere in `controller.cpp`:
```c++
        LOG(INFO) << "Codec: " << headerChunk_->codec << "\n";
        decoder_.reset(nullptr);
        stream_ = nullptr;
        player_.reset(nullptr);

        if (headerChunk_->codec == "pcm")
            decoder_ = make_unique<decoder::PcmDecoder>();
#if defined(HAS_OGG) && (defined(HAS_TREMOR) || defined(HAS_VORBIS))
        else if (headerChunk_->codec == "ogg")
            decoder_ = make_unique<decoder::OggDecoder>();
#endif
#if defined(HAS_FLAC)
        else if (headerChunk_->codec == "flac")
            decoder_ = make_unique<decoder::FlacDecoder>();
#endif
#if defined(HAS_OPUS)
        else if (headerChunk_->codec == "opus")
            decoder_ = make_unique<decoder::OpusDecoder>();
#endif
        else
            throw SnapException("codec not supported: \"" + headerChunk_->codec + "\"");

        sampleFormat_ = decoder_->setHeader(headerChunk_.get());
        LOG(NOTICE) << TAG("state") << "sampleformat: " << sampleFormat_.getFormat() << "\n";
```

If the behavior changes when using a different pcm device, it maybe stucks in `player_.reset(nullptr);`: here alsa is shut down. 
What is the name of the working device and what it the name of the stucking device?
Are you experienced in debugging c++? Or can you add log lines to see where it stucks?

**Comment by sgoudsme** [comment] 2020-03-17 07:33
I do not have any experience in debugging c++. I also installed the software from the .deb package. If I add debug lines, I have to compile it from source, I guess...

**Comment by badaix** [comment] 2020-03-17 11:50
yes, but this is quite well documented.
So your problem is on one client, running in a docker container, with one specific audio device?

**Comment by sgoudsme** [comment] 2020-03-17 12:33
Oke. If I find some time, I will try it.
Yes it is on one client, running in a Docker container, with one audio device.

**Comment by badaix** [comment] 2020-04-14 09:21
could be a duplicate of #569, which turned out not to be an issue. 
Closing this. Please reopen, if not solved.

**Closed by badaix** 2020-04-14 09:21 UTC
