### ISSUE TITLE
Lots of build warnings

### ISSUE THREAD

**Issue by skidoo23** [badaix/snapcast#484] opened 2019-10-17 19:14 UTC
Snapcast 0.16, gcc version 9.2.1 20190909 (Debian 9.2.1-8), Debian testing distro.

```
In file included from player/player.hpp:22,
                 from player/alsa_player.hpp:22,
                 from controller.hpp:30,
                 from snapclient.cpp:24:
../common/aixlog.hpp: In function ‘std::ostream& AixLog::operator<<(std::ostream&, const AixLog::Timestamp&)’:
../common/aixlog.hpp:287:38: warning: ‘sprintf’ may write a terminating nul past the end of the destination [-Wformat-overflow=]
  287 |             sprintf(&ms_str[0], "%03d", ms_part);
      |                                      ^
../common/aixlog.hpp:287:20: note: ‘sprintf’ output between 4 and 5 bytes into a destination of size 4
  287 |             sprintf(&ms_str[0], "%03d", ms_part);
      |             ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by badaix** [comment] 2019-10-18 18:29
should be fixed with this commit e740adacb199bd4bdb07fe951170a9ea3803bd16

**Comment by skidoo23** [comment] 2019-10-19 14:58
Warnings now

```
In file included from control_server.cpp:20:
../common/aixlog.hpp: In function ‘std::ostream& AixLog::operator<<(std::ostream&, const AixLog::Timestamp&)’:
../common/aixlog.hpp:287:38: warning: ‘snprintf’ output may be truncated before the last format character [-Wformat-truncation=]
  287 |             snprintf(ms_str, 4, "%03d", ms_part);
      |                                      ^
../common/aixlog.hpp:287:21: note: ‘snprintf’ output between 4 and 5 bytes into a destination of size 4
  287 |             snprintf(ms_str, 4, "%03d", ms_part);
      |             ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

**Comment by badaix** [comment] 2019-10-19 23:12
I was able to reproduce it with [compiler explorer](https://godbolt.org), seems to be an [gcc bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=78969), this time it's really fixed.

**Closed by badaix** 2019-10-19 23:12 UTC
