### ISSUE TITLE
Issue with librespot

### ISSUE THREAD

**Issue by UMB8998** [badaix/snapcast#1074] opened 2022-11-23 00:34 UTC
Hello I'm trying to run an instance of snapcast server with librespot but the server doesn't start, I have tried with version .26 and .27 and both doesn't seem to work. Attached is the code with version .27, I'm using the realse version of librespot 0.5.0-dev

Thank you

`2022-11-22 18-27-16.724 [Info] (Snapserver) Version 0.27.0
2022-11-22 18-27-16.724 [Info] (Snapserver) Adding source: airplay:///shairport-sync?name=Airplay&devicename=BocinasCasa&port=5000
2022-11-22 18-27-16.724 [Info] (Snapserver) Adding source: spotify:///librespot?name=Spotify&username=XXXXXXX&password=XXXXXXX&devicename=BocinasCasa&bitrate=160&disable_audio_cache=false&killall=true&wd_timeout=1800
2022-11-22 18-27-16.725 [Notice] (init) Settings file: "/home/extraiot/.config/snapserver/server.json"
2022-11-22 18-27-16.727 [Info] (Snapserver) Using HTTP host name: hamoysalame
2022-11-22 18-27-16.740 [Info] (Avahi) Adding service 'Snapcast'
2022-11-22 18-27-16.757 [Info] (PcmStream) PcmStream: Airplay, sampleFormat: 44100:16:2
2022-11-22 18-27-16.758 [Info] (AirplayStream) Metadata support not enabled (HAS_EXPAT not defined)
2022-11-22 18-27-16.758 [Info] (Server) Stream: {"fragment":"","host":"","path":"/shairport-sync","query":{"chunk_ms":"20","codec":"flac","devicename":"BocinasCasa","name":"Airplay","port":"5000","sampleformat":"44100:16:2"},"raw":"airplay:////shairport-sync?chunk_ms=20&codec=flac&devicename=BocinasCasa&name=Airplay&port=5000&sampleformat=44100:16:2","scheme":"airplay"}
2022-11-22 18-27-16.759 [Info] (PcmStream) PcmStream: Spotify, sampleFormat: 44100:16:2
2022-11-22 18-27-16.759 [Info] (Server) Stream: {"fragment":"","host":"","path":"/librespot","query":{"bitrate":"160","chunk_ms":"20","codec":"flac","devicename":"BocinasCasa","disable_audio_cache":"false","killall":"true","name":"Spotify","password":"xxx","sampleformat":"44100:16:2","username":"xxx","wd_timeout":"1800"},"raw":"spotify:////librespot?bitrate=160&chunk_ms=20&codec=flac&devicename=BocinasCasa&disable_audio_cache=false&killall=true&name=Spotify&password=xxx&sampleformat=44100:16:2&username=xxx&wd_timeout=1800","scheme":"spotify"}
2022-11-22 18-27-16.761 [Info] (FlacEnc) Init - compression level: 2
2022-11-22 18-27-16.776 [Error] (AirplayStream) Error opening metadata pipe, retrying in 500ms. Error: assign: Bad file descriptor
2022-11-22 18-27-16.776 [Info] (FlacEnc) Init - compression level: 2
2022-11-22 18-27-16.812 [Info] (Watchdog) Starting watchdog, timeout: 1800s
2022-11-22 18-27-16.812 [Info] (ControlServer) Creating TCP acceptor for address: 0.0.0.0, port: 1705
2022-11-22 18-27-16.812 [Info] (ControlServer) Creating HTTP acceptor for address: 0.0.0.0, port: 1780
2022-11-22 18-27-16.813 [Info] (StreamServer) Creating stream acceptor for address: 0.0.0.0, port: 1704
2022-11-22 18-27-16.813 [Info] (Snapserver) Number of threads: 4, hw threads: 4
2022-11-22 18-27-16.814 [Info] (AirplayStream) (Airplay) Warning: the option -u is no longer needed and is deprecated. Debug and statistics output to STDERR is now the default. Use "--log-to-syslog" to revert.
2022-11-22 18-27-16.818 [Info] (librespot) librespot 0.5.0-dev 2c20669 (Built on 2022-11-13, Build ID: 1W7OJGUS, Profile: release)
2022-11-22 18-27-16.818 [Error] (AirplayStream) username "XXXXXXXX"
2022-11-22 18-27-16.824 [Info] (librespot_playback::mixer::softmixer) Mixing with softvol and volume control: Log(60.0)
2022-11-22 18-27-16.826 [Info] (librespot_playback::convert) Converting with ditherer: tpdf
2022-11-22 18-27-16.826 [Info] (librespot_playback::audio_backend::pipe) Using StdoutSink (pipe) with format: S16
2022-11-22 18-27-16.949 [Info] (librespot_core::session) Connecting to AP "ap-guc3.spotify.com:4070"
2022-11-22 18-27-17.260 [Info] (librespot_core::session) Authenticated as "XXXXXXXXXX" !
2022-11-22 18-27-17.261 [Info] (librespot_core::session) Country: "MX"
2022-11-22 18-27-17.262 [Info] (LibrespotStream) (Spotify)         "image-url": "https://i.scdn.co/image/{file_id}",
2022-11-22 18-27-17.262 [Info] (LibrespotStream) (Spotify)         "enable-annotations-read": "0",
2022-11-22 18-27-17.262 [Info] (LibrespotStream) (Spotify)         "ab-mobile-social-feed": "1",
2022-11-22 18-27-17.262 [Info] (LibrespotStream) (Spotify)         "incognito_mode_timeout": "21600",
2022-11-22 18-27-17.263 [Info] (LibrespotStream) (Spotify)         "ads": "0",
2022-11-22 18-27-17.263 [Info] (LibrespotStream) (Spotify)         "sidebar-navigation-enabled": "0",
2022-11-22 18-27-17.263 [Info] (LibrespotStream) (Spotify)         "enable-autostart": "1",
2022-11-22 18-27-17.263 [Info] (LibrespotStream) (Spotify)         "ab-collection-followed-artists-only": "1",
2022-11-22 18-27-17.263 [Info] (LibrespotStream) (Spotify)         "ab_recently_played_feature_time_filter_threshold": "com.spotify.gaia=30,driving-mode=120,spotify%3Ainternal%3Astartpage=30",
2022-11-22 18-27-17.263 [Info] (LibrespotStream) (Spotify)         "prefetch-keys": "1",
2022-11-22 18-27-17.263 [Info] (LibrespotStream) (Spotify)         "ab-desktop-hide-follow": "0",
2022-11-22 18-27-17.263 [Info] (LibrespotStream) (Spotify)         "publish-activity": "0",
2022-11-22 18-27-17.263 [Info] (LibrespotStream) (Spotify)         "widevine-license-url": "https://spclient.wg.spotify.com/widevine-license/v1/video/license",
2022-11-22 18-27-17.264 [Info] (LibrespotStream) (Spotify)         "ab-watch-now": "0",
2022-11-22 18-27-17.264 [Info] (LibrespotStream) (Spotify)         "ab-mobile-running-onlymanualmode": "only-manual",
2022-11-22 18-27-17.264 [Info] (LibrespotStream) (Spotify)         "fb-info-confirmation": "control",
2022-11-22 18-27-17.264 [Info] (LibrespotStream) (Spotify)         "financial-product": "pr:premium,tc:0,rt:v2_MX_default_new-family-sub-1m_0_MXN_default",
2022-11-22 18-27-17.264 [Info] (LibrespotStream) (Spotify)         "head-files-url": "http://heads-fa.spotify.com/head/{file_id}",
2022-11-22 18-27-17.264 [Info] (LibrespotStream) (Spotify)         "high-bitrate": "1",
2022-11-22 18-27-17.265 [Info] (LibrespotStream) (Spotify)         "mobile-login": "1",
2022-11-22 18-27-17.265 [Info] (LibrespotStream) (Spotify)         "default-play-bitrate": "24000",
2022-11-22 18-27-17.265 [Info] (LibrespotStream) (Spotify)         "storage-size-config": "10240,90,500,3",
2022-11-22 18-27-17.265 [Info] (LibrespotStream) (Spotify)         "npt-disabled": "2",
2022-11-22 18-27-17.265 [Info] (LibrespotStream) (Spotify)         "ad-formats-preroll-video": "0",
2022-11-22 18-27-17.265 [Info] (LibrespotStream) (Spotify)         "key-caching-max-count": "10000",
2022-11-22 18-27-17.266 [Info] (LibrespotStream) (Spotify)         "ab-collection-offline-mode": "0",
2022-11-22 18-27-17.266 [Info] (LibrespotStream) (Spotify)         "offline": "1",
2022-11-22 18-27-17.266 [Info] (LibrespotStream) (Spotify)         "allow-override-internal-prefs": "0",
2022-11-22 18-27-17.266 [Info] (LibrespotStream) (Spotify)         "shuffle": "0",
2022-11-22 18-27-17.266 [Info] (LibrespotStream) (Spotify)         "ab-play-history": "0",
2022-11-22 18-27-17.266 [Info] (LibrespotStream) (Spotify)         "instant-search": "0",
2022-11-22 18-27-17.266 [Info] (LibrespotStream) (Spotify)         "arsenal_country": "1",
2022-11-22 18-27-17.266 [Info] (LibrespotStream) (Spotify)         "send-email": "1",
2022-11-22 18-27-17.267 [Info] (LibrespotStream) (Spotify)         "catalogue": "premium",
2022-11-22 18-27-17.267 [Info] (LibrespotStream) (Spotify)         "india-experience": "0",
2022-11-22 18-27-17.267 [Info] (LibrespotStream) (Spotify)         "video-keyframe-url": "http://keyframes-fa.cdn.spotify.com/keyframes/v1/sources/{source_id}/keyframe/heights/{height}/timestamps/{timestamp_ms}.jpg",
2022-11-22 18-27-17.267 [Info] (LibrespotStream) (Spotify)         "browse-overview-enabled": "1",
2022-11-22 18-27-17.267 [Info] (LibrespotStream) (Spotify)         "ab-ad-player-targeting": "1",
2022-11-22 18-27-17.267 [Info] (LibrespotStream) (Spotify)         "collection": "1",
2022-11-22 18-27-17.267 [Info] (LibrespotStream) (Spotify)         "shows-collection-jam": "0",
2022-11-22 18-27-17.267 [Info] (LibrespotStream) (Spotify)         "ab-new-share-flow": "0",
2022-11-22 18-27-17.268 [Info] (LibrespotStream) (Spotify)         "shows-collection": "0",
2022-11-22 18-27-17.268 [Info] (LibrespotStream) (Spotify)         "shuffle-algorithm": "1",
2022-11-22 18-27-17.268 [Info] (LibrespotStream) (Spotify)         "use-pl3": "0",
2022-11-22 18-27-17.268 [Info] (LibrespotStream) (Spotify)         "name": "Spotify Premium",
2022-11-22 18-27-17.268 [Info] (LibrespotStream) (Spotify)         "video-manifest-url": "https://spclient.wg.spotify.com/manifests/v3/{type}/sources/{source_id}",
2022-11-22 18-27-17.268 [Info] (LibrespotStream) (Spotify)         "ab-collection-hide-unavailable-albums": "0",
2022-11-22 18-27-17.269 [Info] (LibrespotStream) (Spotify)         "head-file-caching": "1",
2022-11-22 18-27-17.269 [Info] (LibrespotStream) (Spotify)         "license-acceptance-grace-days": "30",
2022-11-22 18-27-17.269 [Info] (LibrespotStream) (Spotify)         "ab-moments-experience": "0",
2022-11-22 18-27-17.269 [Info] (LibrespotStream) (Spotify)         "ab-test-group": "966",
2022-11-22 18-27-17.269 [Info] (LibrespotStream) (Spotify)         "metadata-link-lookup-modes": "0",
2022-11-22 18-27-17.270 [Info] (LibrespotStream) (Spotify)         "head-files": "1",
2022-11-22 18-27-17.270 [Info] (LibrespotStream) (Spotify)         "mobile-payment": "0",
2022-11-22 18-27-17.270 [Info] (LibrespotStream) (Spotify)         "network-operator-premium-activation": "1",
2022-11-22 18-27-17.270 [Info] (LibrespotStream) (Spotify)         "payments-locked-state": "0",
2022-11-22 18-27-17.270 [Info] (LibrespotStream) (Spotify)         "preferred-locale": "en",
2022-11-22 18-27-17.270 [Info] (LibrespotStream) (Spotify)         "on-demand": "1",
2022-11-22 18-27-17.270 [Info] (LibrespotStream) (Spotify)         "ab-mobile-running-tempo-detection": "Control",
2022-11-22 18-27-17.271 [Info] (LibrespotStream) (Spotify)         "payments-initial-campaign": "default",
2022-11-22 18-27-17.271 [Info] (LibrespotStream) (Spotify)         "lastfm-session": "",
2022-11-22 18-27-17.271 [Info] (LibrespotStream) (Spotify)         "use-fb-publish-backend": "2",
2022-11-22 18-27-17.271 [Info] (LibrespotStream) (Spotify)         "products": "",
2022-11-22 18-27-17.271 [Info] (LibrespotStream) (Spotify)         "video-initial-bitrate": "200000",
2022-11-22 18-27-17.271 [Info] (LibrespotStream) (Spotify)         "user-profile-show-invitation-codes": "0",
2022-11-22 18-27-17.272 [Info] (LibrespotStream) (Spotify)         "radio": "1",
2022-11-22 18-27-17.272 [Info] (LibrespotStream) (Spotify)         "product": "",
2022-11-22 18-27-17.272 [Info] (LibrespotStream) (Spotify)         "explicit-content": "1",
2022-11-22 18-27-17.272 [Info] (LibrespotStream) (Spotify)         "publish-playlist": "1",
2022-11-22 18-27-17.272 [Info] (LibrespotStream) (Spotify)         "mobile": "1",
2022-11-22 18-27-17.273 [Info] (LibrespotStream) (Spotify)         "wanted-licenses": "",
2022-11-22 18-27-17.273 [Info] (LibrespotStream) (Spotify)         "buffering-strategy": "2",
2022-11-22 18-27-17.273 [Info] (LibrespotStream) (Spotify)         "playlist-folders": "1",
2022-11-22 18-27-17.273 [Info] (LibrespotStream) (Spotify)         "ad-persist-reward-time": "0",
2022-11-22 18-27-17.273 [Info] (LibrespotStream) (Spotify)         "streaming-rules": "",
2022-11-22 18-27-17.273 [Info] (LibrespotStream) (Spotify)         "playlist-annotations-markup": "0",
2022-11-22 18-27-17.274 [Info] (LibrespotStream) (Spotify)         "ugc-abuse-report-url": "https://support.spotify.com/abuse/?uri={uri}",
2022-11-22 18-27-17.274 [Info] (LibrespotStream) (Spotify)         "app-developer": "0",
2022-11-22 18-27-17.274 [Info] (LibrespotStream) (Spotify)         "capper-profile": "",
2022-11-22 18-27-17.274 [Info] (LibrespotStream) (Spotify)         "is_email_verified": "0",
2022-11-22 18-27-17.274 [Info] (LibrespotStream) (Spotify)         "ad-session-persistence": "1",
2022-11-22 18-27-17.274 [Info] (LibrespotStream) (Spotify)         "track-cap": "0",
2022-11-22 18-27-17.274 [Info] (LibrespotStream) (Spotify)         "created_by_partner": "",
2022-11-22 18-27-17.274 [Info] (LibrespotStream) (Spotify)         "ab-browse-music-tuesday": "1",
2022-11-22 18-27-17.275 [Info] (LibrespotStream) (Spotify)         "type": "premium",
2022-11-22 18-27-17.275 [Info] (LibrespotStream) (Spotify)         "license-agreements": "",
2022-11-22 18-27-17.275 [Info] (LibrespotStream) (Spotify)         "ap-resolve-pods": "0",
2022-11-22 18-27-17.275 [Info] (LibrespotStream) (Spotify)         "audio-preview-url-template": "https://p.scdn.co/mp3-preview/{id}",
2022-11-22 18-27-17.275 [Info] (LibrespotStream) (Spotify)         "streaming": "1",
2022-11-22 18-27-17.275 [Info] (LibrespotStream) (Spotify)         "enable-crossfade": "1",
2022-11-22 18-27-17.275 [Info] (LibrespotStream) (Spotify)         "enable-gapless": "1",
2022-11-22 18-27-17.275 [Info] (LibrespotStream) (Spotify)         "ab-collection-union": "1",
2022-11-22 18-27-17.276 [Info] (LibrespotStream) (Spotify)         "buffering-strategy-parameters": "0.8:0.2:0.0:0.0:0.0:0.0:1.0:10:10:2000:10000:10485760",
2022-11-22 18-27-17.276 [Info] (LibrespotStream) (Spotify)         "prefetch-strategy": "18",
2022-11-22 18-27-17.276 [Info] (LibrespotStream) (Spotify)         "video-wifi-initial-bitrate": "800000",
2022-11-22 18-27-17.276 [Info] (LibrespotStream) (Spotify)         "ab-mobile-startpage": "0",
2022-11-22 18-27-17.276 [Info] (LibrespotStream) (Spotify)         "prefetch-window-max": "2",
2022-11-22 18-27-17.276 [Info] (LibrespotStream) (Spotify)         "remote-control": "0",
2022-11-22 18-27-17.276 [Info] (LibrespotStream) (Spotify)         "player-license": "premium",
2022-11-22 18-27-17.276 [Info] (LibrespotStream) (Spotify)         "mobile-browse": "0",
2022-11-22 18-27-17.276 [Info] (LibrespotStream) (Spotify)         "ad-formats-video-takeover": "0",
2022-11-22 18-27-17.276 [Info] (LibrespotStream) (Spotify)         "local-files-import": "0",
2022-11-22 18-27-17.276 [Info] (LibrespotStream) (Spotify)         "key-caching-max-offline-seconds": "1800",
2022-11-22 18-27-17.276 [Info] (LibrespotStream) (Spotify)         "use-playlist-uris": "0",
2022-11-22 18-27-17.276 [Info] (LibrespotStream) (Spotify)         "ugc-abuse-report": "0",
2022-11-22 18-27-17.277 [Info] (LibrespotStream) (Spotify)         "ab-sugarpills-sanity-check": "0",
2022-11-22 18-27-17.277 [Info] (LibrespotStream) (Spotify)         "libspotify": "1",
2022-11-22 18-27-17.277 [Info] (LibrespotStream) (Spotify)         "video-device-blacklisted": "0",
2022-11-22 18-27-17.277 [Info] (LibrespotStream) (Spotify)         "ab-collection-bookmark-model": "1",
2022-11-22 18-27-17.277 [Info] (LibrespotStream) (Spotify)         "ab-android-push-notifications": "1",
2022-11-22 18-27-17.277 [Info] (LibrespotStream) (Spotify)         "fb-grant-permission-local-render": "0",
2022-11-22 18-27-17.277 [Info] (LibrespotStream) Error opening metadata pipe, retrying in 500ms. Error: assign: Bad file descriptor
2022-11-22 18-27-17.277 [Info] (LibrespotStream) (Spotify)         "instant-search-expand-sidebar": "0",
2022-11-22 18-27-17.277 [Info] (LibrespotStream) (Spotify)         "ab-mobile-discover": "0",
2022-11-22 18-27-17.277 [Info] (LibrespotStream) (Spotify)         "nft-disabled": "1",
2022-11-22 18-27-17.277 [Info] (LibrespotStream) (Spotify)         "video-cdn-sampling": "1",
2022-11-22 18-27-17.277 [Info] (LibrespotStream) (Spotify)         "pause-after": "0",
2022-11-22 18-27-17.278 [Info] (LibrespotStream) (Spotify)         "capping-bar-threshold": "3601",
2022-11-22 18-27-17.278 [Info] (LibrespotStream) (Spotify)         "unrestricted": "1",
2022-11-22 18-27-17.278 [Info] (LibrespotStream) (Spotify)         "expiry": "1",
2022-11-22 18-27-17.278 [Info] (LibrespotStream) (Spotify)     }
2022-11-22 18-27-17.366 [Info] (LibrespotStream) (Spotify)     ident: "11af42bf69d6e3e654db4044f3a8181a31cc050f"
2022-11-22 18-27-17.368 [Info] (LibrespotStream) (Spotify)     protocol_version: "2.0.0"
2022-11-22 18-27-17.369 [Info] (LibrespotStream) (Spotify)     seq_nr: 568443572
2022-11-22 18-27-17.369 [Info] (LibrespotStream) (Spotify)     typ: kMessageTypeNotify
2022-11-22 18-27-17.369 [Info] (LibrespotStream) (Spotify)     device_state {
2022-11-22 18-27-17.369 [Info] (LibrespotStream) (Spotify)       sw_version: "harmony:4.27.1-af7f4f3/track-playback"
2022-11-22 18-27-17.369 [Info] (LibrespotStream) (Spotify)       is_active: false
2022-11-22 18-27-17.370 [Info] (LibrespotStream) (Spotify)       can_play: true
2022-11-22 18-27-17.370 [Info] (LibrespotStream) (Spotify)       volume: 65535
2022-11-22 18-27-17.370 [Info] (LibrespotStream) (Spotify)       name: "Web Player (Chrome)"
2022-11-22 18-27-17.370 [Info] (LibrespotStream) (Spotify)       capabilities {
2022-11-22 18-27-17.370 [Info] (LibrespotStream) (Spotify)         typ: kCanBePlayer
2022-11-22 18-27-17.370 [Info] (LibrespotStream) (Spotify)         intValue: 1
2022-11-22 18-27-17.370 [Info] (LibrespotStream) (Spotify)       }
2022-11-22 18-27-17.370 [Info] (LibrespotStream) (Spotify)       capabilities {
2022-11-22 18-27-17.370 [Info] (LibrespotStream) (Spotify)         typ: kRestrictToLocal
2022-11-22 18-27-17.370 [Info] (LibrespotStream) (Spotify)         intValue: 0
2022-11-22 18-27-17.370 [Info] (LibrespotStream) (Spotify)       }
2022-11-22 18-27-17.371 [Info] (LibrespotStream) (Spotify)       capabilities {
2022-11-22 18-27-17.371 [Info] (LibrespotStream) (Spotify)         typ: kGaiaEqConnectId
2022-11-22 18-27-17.371 [Info] (LibrespotStream) (Spotify)         intValue: 1
2022-11-22 18-27-17.371 [Info] (LibrespotStream) (Spotify)       }
2022-11-22 18-27-17.371 [Info] (LibrespotStream) (Spotify)       capabilities {
2022-11-22 18-27-17.371 [Info] (LibrespotStream) (Spotify)         typ: kSupportsLogout
2022-11-22 18-27-17.371 [Info] (LibrespotStream) (Spotify)         intValue: 1
2022-11-22 18-27-17.371 [Info] (LibrespotStream) (Spotify)       }
2022-11-22 18-27-17.371 [Info] (LibrespotStream) (Spotify)       capabilities {
2022-11-22 18-27-17.371 [Info] (LibrespotStream) (Spotify)         typ: kIsObservable
2022-11-22 18-27-17.371 [Info] (LibrespotStream) (Spotify)         intValue: 1
2022-11-22 18-27-17.371 [Info] (LibrespotStream) (Spotify)       }
2022-11-22 18-27-17.371 [Info] (LibrespotStream) (Spotify)       capabilities {
2022-11-22 18-27-17.371 [Info] (LibrespotStream) (Spotify)         typ: kCommandAcks
2022-11-22 18-27-17.371 [Info] (LibrespotStream) (Spotify)         intValue: 1
2022-11-22 18-27-17.371 [Info] (LibrespotStream) (Spotify)       }
2022-11-22 18-27-17.371 [Info] (LibrespotStream) (Spotify)       capabilities {
2022-11-22 18-27-17.371 [Info] (LibrespotStream) (Spotify)         typ: kSupportsRename
2022-11-22 18-27-17.371 [Info] (LibrespotStream) (Spotify)         intValue: 0
2022-11-22 18-27-17.371 [Info] (LibrespotStream) (Spotify)       }
2022-11-22 18-27-17.371 [Info] (LibrespotStream) (Spotify)       capabilities {
2022-11-22 18-27-17.371 [Info] (LibrespotStream) (Spotify)         typ: kHidden
2022-11-22 18-27-17.371 [Info] (LibrespotStream) (Spotify)         intValue: 0
2022-11-22 18-27-17.371 [Info] (LibrespotStream) (Spotify)       }
2022-11-22 18-27-17.372 [Info] (LibrespotStream) (Spotify)       capabilities {
2022-11-22 18-27-17.372 [Info] (LibrespotStream) (Spotify)         typ: kDeviceType
2022-11-22 18-27-17.372 [Info] (LibrespotStream) (Spotify)         intValue: 1
2022-11-22 18-27-17.372 [Info] (LibrespotStream) (Spotify)       }
2022-11-22 18-27-17.373 [Info] (LibrespotStream) (Spotify)       capabilities {
2022-11-22 18-27-17.373 [Info] (LibrespotStream) (Spotify)         typ: kVolumeSteps
2022-11-22 18-27-17.373 [Info] (LibrespotStream) (Spotify)         intValue: 64
2022-11-22 18-27-17.373 [Info] (LibrespotStream) (Spotify)       }
2022-11-22 18-27-17.373 [Info] (LibrespotStream) (Spotify)       capabilities {
2022-11-22 18-27-17.374 [Info] (LibrespotStream) (Spotify)         typ: kSupportsPlaylistV2
2022-11-22 18-27-17.374 [Info] (LibrespotStream) (Spotify)         intValue: 0
2022-11-22 18-27-17.374 [Info] (LibrespotStream) (Spotify)       }
2022-11-22 18-27-17.374 [Info] (LibrespotStream) (Spotify)       capabilities {
2022-11-22 18-27-17.374 [Info] (LibrespotStream) (Spotify)         typ: kSupportsExternalEpisodes
2022-11-22 18-27-17.374 [Info] (LibrespotStream) (Spotify)         intValue: 1
2022-11-22 18-27-17.374 [Info] (LibrespotStream) (Spotify)       }
2022-11-22 18-27-17.374 [Info] (LibrespotStream) (Spotify)       capabilities {
2022-11-22 18-27-17.374 [Info] (LibrespotStream) (Spotify)         typ: kSupportedTypes
2022-11-22 18-27-17.374 [Info] (LibrespotStream) (Spotify)         stringValue: "audio/track"
2022-11-22 18-27-17.374 [Info] (LibrespotStream) (Spotify)         stringValue: "audio/episode"
2022-11-22 18-27-17.374 [Info] (LibrespotStream) (Spotify)         stringValue: "video/episode"
2022-11-22 18-27-17.375 [Info] (LibrespotStream) (Spotify)         stringValue: "mixed/episode"
2022-11-22 18-27-17.375 [Info] (LibrespotStream) (Spotify)       }
2022-11-22 18-27-17.375 [Info] (LibrespotStream) (Spotify)       metadata {
2022-11-22 18-27-17.375 [Info] (LibrespotStream) (Spotify)         type: "client_id"
2022-11-22 18-27-17.375 [Info] (LibrespotStream) (Spotify)         metadata: "XXXXXXXXX"
2022-11-22 18-27-17.375 [Info] (LibrespotStream) metadata: < "XXXXXXXXXX">
terminate called after throwing an instance of 'nlohmann::detail::type_error'
  what():  [json.exception.type_error.305] cannot use operator[] with a string argument with string
Aborted`

**Comment by badaix** [comment] 2023-02-05 12:29
duplicate of #1063 
Fixed in [snapcast v0.27.0](https://github.com/badaix/snapcast/releases/tag/v0.27.0)

**Closed by badaix** 2023-02-05 12:29 UTC
Labels: duplicate, next release
