### ISSUE TITLE
Snapserver fails to start on dietpi installation "Exception: failed to open file "/var/lib/snapserver/server.json", permission denied (error 13)"

### ISSUE THREAD

**Issue by isaacwisdom** [badaix/snapcast#888] opened 2021-06-09 23:21 UTC
Snapserver fails to start automatically with systemd or dietpi-services. No problems when started manually through CLI.
Fixing the permissions manually with `chmod 777 /var/lib/snapserver/server.json` fixes the problem.

**Steps to Reproduce**
1. Install snapserver from installation pages
2. Allow process to be started on boot by either systemd or dietpi-services

**Environment details**
- OS: DietPi v7.2.3
- Snapcast version v0.25.0
- Installed from package on releases page

Running "journalctl -u snapserver.service" gives:
```log
……
Jun 10 00:05:36 DietPi systemd[1]: Started Snapcast server.
Jun 10 00:05:36 DietPi snapserver[737]: Version 0.25.0, revision 2af5292f
Jun 10 00:05:36 DietPi snapserver[737]: Adding source: pipe:///tmp/snapfifo?name=default
Jun 10 00:05:36 DietPi snapserver[737]: Settings file: "/var/lib/snapserver/server.json"
Jun 10 00:05:36 DietPi snapserver[737]: Exception: failed to open file "/var/lib/snapserver/server.json", permission denied (error 13)
Jun 10 00:05:36 DietPi snapserver[737]: Snapserver terminated.
Jun 10 00:05:36 DietPi systemd[1]: snapserver.service: Main process exited, code=exited, status=1/FAILURE
……
```

**Comment by badaix** [comment] 2021-06-10 06:17
Possible duplicate of #863 
You can 
- try to manually fix the permission problems or 
- [vote for Snapcast integration into DietPi](https://feathub.com/MichaIng/DietPi)
- change the `server.json` location in `snapserver.conf`: 

```
# General server settings #####################################################
#
[server]
# Number of additional worker threads to use
# - For values < 0 the number of threads will be 2 (on single and dual cores)
#   or 4 (for quad and more cores)
# - 0 will utilize just the processes main thread and might cause audio drops 
#   in case there are a couple of longer running tasks, such as encoding 
#   multiple audio streams
#threads = -1

# the pid file when running as daemon
#pidfile = /var/run/snapserver/pid

# the user to run as when daemonized
#user = snapserver
# the group to run as when daemonized
#group = snapserver

# directory where persistent data is stored (server.json)
# if empty, data dir will be
#  - "/var/lib/snapserver/" when running as daemon
#  - "$HOME/.config/snapserver/" when not running as daemon
#datadir = 

#
###############################################################################
```

**Closed** 2021-06-15 08:43 UTC
