### ISSUE TITLE
F-droid repo

### ISSUE THREAD

**Issue by lhupitr** [badaix/snapcast#235] opened 2017-04-22 05:11 UTC
Will new versions continue to be pushed to the F-Droid repository? I'm still on 0.7 which is no longer compatible with the versions I'm running on linux.

**Comment by badaix** [comment] 2017-04-22 09:30
Don't know. I'm not the maintainer of the APK in F-Droid. 
Actually, I'm thinking from time to time to release it in the Google play store.

**Comment by pille** [comment] 2017-04-22 09:48
i think the problem is that they couln't build it the last time and disabled autobuilds.
if you put them back on the right track, it will maintain itself.
i'd like to see it more in f-droid, rather than play. the latter may be optional.

**Comment by lhupitr** [comment] 2017-04-22 15:52
OK thanks, I'll have to sit down and go through the compilation instructions.
And, yes, another vote for f-droid rather than play-

**Comment by lhupitr** [comment] 2017-04-24 18:42
I've followed all the Snapcast Android cross compile instructions but I'm not sure what to do next in order to push it to my device. Do I make an apk package (if so how?) or just push the executable binary somewhere (if so where?). Apologies, I've never done this before.

**Comment by RoXXoR** [comment] 2017-04-30 10:53
@lhupitr  You can just download the released apk from @badaix (https://github.com/badaix/snapcast/releases) directly to your phone and install it.

**Comment by lhupitr** [comment] 2017-05-01 21:07
Ah, I didn't see that, sorry.

**Comment by slackline** [comment] 2017-05-27 11:56
Current Android release (v0.11.1) works great.  I too would appreciate seeing it in F-Droid repo though so that updates happen automatically.  Sounds like its a problem with the F-Droid autobuild as @pille suggests.

**Comment by MayeulC** [comment] 2018-04-21 20:00
Hi, has there been any progress on this?

**Comment by rcmcronny** [comment] 2018-07-17 06:50
No 0.15.0 apk available and f droid seems outdated to, any progress here, it would be really great to have snapcast in f-droid 👍

**Comment by derlucas** [comment] 2018-12-08 15:41
I think F-Droid stopped updating because of an builderror:

https://gitlab.com/fdroid/fdroiddata/commit/51615321219c271a1a5b744675c9200cec852253
https://gitlab.com/fdroid/fdroiddata/commit/d9b0d85ff85b96d01cbe2c686013b799b952c57a

**Comment by badaix** [comment] 2020-03-11 09:55
Closing this as it is a Snapdroid related issue. Cross compilation of the Snapclient binaries for Android is quite complicated and not automated. Someone must spend some effort here.

**Closed by badaix** 2020-03-11 09:55 UTC
