### ISSUE TITLE
0.26.0 installs meta_mpd.py with executable permissions only

### ISSUE THREAD

**Issue by yurivict** [badaix/snapcast#1021] opened 2022-06-19 06:37 UTC
```
$ ls -l ./work/stage/usr/local/share/snapserver/plug-ins/meta_mpd.py
---x--x--x  1 yuri  wheel  33278 Dec 22 09:40 ./work/stage/usr/local/share/snapserver/plug-ins/meta_mpd.py
```

**Comment by badaix** [comment] 2022-06-19 16:57
Could you be a bit more specific? 
What OS? 
How did you install it?

**Comment by yurivict** [comment] 2022-06-19 17:16
OS: FreeBSD 13.1

Installed using the FreeBSD ports framework. It just uses the 'install' target.

**Comment by badaix** [comment] 2022-06-19 18:05
Cmake install or make install?

**Comment by yurivict** [comment] 2022-06-19 18:07
cmake

**Comment by badaix** [comment] 2022-06-24 08:28
duplicate of #970

**Comment by badaix** [comment] 2022-07-04 16:52
fixed in 7ab3daa76d9bd2700b609162c6cbe47351e535d0

**Comment by badaix** [comment] 2023-02-05 12:31
Fixed in [snapcast v0.27.0](https://github.com/badaix/snapcast/releases/tag/v0.27.0)

**Closed** 2023-02-05 12:33 UTC
Labels: bug, next release
