### ISSUE TITLE
White noise

### ISSUE THREAD

**Issue by ghost** [badaix/snapcast#51] opened 2016-04-19 20:19 UTC
Hi :)
First I tried installing the deb. I used the arm version on a raspi B+
That resulted in only white noise from mopidy and .wav files.
Next I tried compiling from source(same pi).
It gave white noise for the wav test but I could make out the song playing with mopidy faintly, also engulfed by white noise.
Clients:

 - LMDE2(.deb package)
 - Android phone(.apk)

The white noise from the two clients are also different, and not just time delay, actually different noises.

The Pi is connected via a switch to the AP serving the clients. I have a local client installed from source on the Pi itself, but I haven't found speakers to hook up to it yet. Wifi network is 150Mbps, but on iwconfig  Bit Rate=11 Mb/s

**Comment by erasmuswill** [comment] 2016-04-19 21:14
It turns out I was on an old mopidy version. When I upgraded, it started playing a lot better, but only on the Android client. It still has a bit of quiet space here and there, but I think this is because I'm streaming.  The laptop client has quiet space almost all the time, and here and there there is a highly sped up portion of the song, presumably to account for the lag? It did however play nicely for a few seconds in conjunction with my Android, which was magical, even if it was a tiny bit out of sync.

**Comment by badaix** [comment] 2016-04-21 07:51
11 MB/s should be fine. But it sounds anyways like a bad network connection. Can you ping the server (RPI) from the Client (LMDE2)?

**Comment by erasmuswill** [comment] 2016-05-02 19:39
Yes I can. I was installing and running the client in a screen session over SSH

**Comment by badaix** [comment] 2016-07-29 06:57
Closing old, non reproducible issue. Please reopen if the problem still exists.

**Closed by badaix** 2016-07-29 06:57 UTC

**Comment by ashwinvandijk** [comment] 2017-04-15 10:16
I have the same problem. When I stop the music for 5 seconds, and then start again most of the time the problem is fixed. All my clients are connected by cable, so I don't think it has something to do with my network...

**Comment by ashwinvandijk** [comment] 2017-05-03 08:24
Still happens. I'd rather have no sound than the white noise, because it's always on full volume. Anything we can do here?
