### ISSUE TITLE
JSON API Documentation and API Feature Requests

### ISSUE THREAD

**Issue by sashahilton00** [badaix/snapcast#157] opened 2017-01-07 01:48 UTC
Is there any official documentation for the JSON RPC API, or is one expected to look at the code and work it out accordingly? Just wondering if I am missing something. If there is no documentation, please consider this a feature request, as it would be nice to integrate snapcast with 3rd party apps. Likewise, a couple of features that would be great to have in the API would be:

- Create/delete new pipe/stream whilst server is started
- Client Grouping (I know this is on the to-do) - Muting/Switch Stream/etc.
- Disconnecting Clients

**Comment by unimatrix27** [comment] 2017-01-09 15:49
Hi,

there is a documentation in /doc/json_rpc_api which simply lists all the JSON snippets that are relevant. 

Be aware that this is not JSON over HTTP, but newline-delimited JSON over raw TCP. 

A good way to understand how it works is to install the Android Client and then simply monitor the raw traffic between the client and the server using tcpflow or wireshark. If you are running snapserver on linux, just install tcpflow and with the command "tcpflow -c port 1705" you should be able to watch the JSON lines going back and forth. There is just a handfull of commands and replies. The detailed structure of those are in the documentation here.

A third-party app should first get the status from the server using the Server.GetStatus request. A third party app needs to connect to port 1705 and leave this connection open all the time. The Server also sends lines here, if its status changes triggered by other clients, etc.

**Comment by sashahilton00** [comment] 2017-01-18 23:42
Thanks for the info, will install bluestacks and monitor snapserver. With regards to the feature requests and documentation, is there a roadmap anywhere besides te checklist on the front page?

**Comment by unimatrix27** [comment] 2017-01-18 23:45
Dont know about the roadmap but i could  post a capture tomorrow of the communication between my own app and snapcast which would  probably just explain itself.

**Comment by badaix** [comment] 2017-03-15 19:59
There is a list of all available Entities, Requests and Notifications [here](https://github.com/badaix/snapcast/blob/master/doc/json_rpc_api/v2_0_0.md).
It's still not good enough to call it a specification, but it might be a starting point.
Regarding the roadmap: there is only the checklist :). In the end Snapcast is still a spare time project.
I will close this issue, as it is not solved, but kind of a duplicate of #22

**Closed by badaix** 2017-03-15 19:59 UTC
