### ISSUE TITLE
--sampleformat no longer works

### ISSUE THREAD

**Issue by maweki** [badaix/snapcast#103] opened 2016-09-04 15:41 UTC
The samplerate argument no longer works. One has to use the uri to set the samplerate like: `snapserver -s pipe:///tmp/snapfifo?name=desktop\&sampleformat=44100:16:2` instead of `snapserver --samplerate 44100:16:2`

**Comment by badaix** [comment] 2016-09-07 17:43
the option is actually called `sampleformat`:

````
$ ./snapserver -h
Allowed options:
  -h, --help                          Produce help message
  -v, --version                       Show version number
  -p, --port arg (=1704)              Server port
  --controlPort arg (=1705)           Remote control port
  -s, --stream arg (=pipe:///tmp/snapfifo?name=default)
                                      URI of the PCM input stream.
                                      Format: TYPE://host/path?name=NAME
                                      [&codec=CODEC]
                                      [&sampleformat=SAMPLEFORMAT]
  --sampleformat arg (=48000:16:2)    Default sample format
  -c, --codec arg (=flac)             Default transport codec
                                      (flac|ogg|pcm)[:options]
                                      Type codec:? to get codec specific options
  --streamBuffer arg (=20)            Default stream read buffer [ms]
  -b, --buffer arg (=1000)            Buffer [ms]
  -d, --daemon [=arg(=0)]             Daemonize
                                      optional process priority [-20..19]
````

**Comment by maweki** [comment] 2016-09-07 20:15
I am sorry. But that doesn't work either

```
$ snapserver --sampleformat 44100:16:2
Settings file: /home/maweki/.config/snapcast/server.json
2016-09-07 22-06-31 [out] Adding service 'Snapcast'
2016-09-07 22-06-31 [out] PcmStream sampleFormat: 48000:16:2
```

The thing that actually works is adding the sampleformat to the streaming url: 

```
SNAPSERVER_OPTS="-s pipe:///tmp/snapfifo?name=mawekidesktop&sampleformat=44100:16:2 -d"
```

in `0.8.0` the sampleformat argument isn't actually parsed. It is taken from the streaming url and from nowhere else.

**Comment by badaix** [comment] 2016-09-08 14:48
I cannot reproduce it. It is parsed and stored (with default) in `Value<string> sampleFormatValue` by the option parser:
`Value<string> sampleFormatValue("", "sampleformat", "Default sample format", settings.sampleFormat);`

some lines further down the option parser's value is assigned to `settings.sampleFormat`:
`settings.sampleFormat = sampleFormatValue.getValue();`

when I start the server as you did, I get the expected behaviour:

Default (48 kHz):
````
$ ./snapserver
Settings file: /home/johannes/.config/snapcast/server.json
2016-09-08 16-39-52 [out] Adding service 'Snapcast'
2016-09-08 16-39-52 [out] PcmStream sampleFormat: 48000:16:2
````

Configured to 44.1 kHz:
````
$ ./snapserver --sampleformat 44100:16:2
Settings file: /home/johannes/.config/snapcast/server.json
2016-09-08 16-39-45 [out] Adding service 'Snapcast'
2016-09-08 16-39-45 [out] PcmStream sampleFormat: 44100:16:2
````

Configured to 48 kHz:
````
$ ./snapserver --sampleformat 48000:16:2
Settings file: /home/johannes/.config/snapcast/server.json
2016-09-08 16-39-58 [out] Adding service 'Snapcast'
2016-09-08 16-39-58 [out] PcmStream sampleFormat: 48000:16:2
````

**Comment by maweki** [comment] 2016-09-08 15:20
I don't know what the issue is. I tested it both with `master` and `0.8.0`. I set a different locale but

```
$ LANG=C ./snapserver --sampleformat 44100:16:2
Settings file: /home/maweki/.config/snapcast/server.json
2016-09-08 17-19-41 [out] Adding service 'Snapcast'
2016-09-08 17-19-41 [out] PcmStream sampleFormat: 48000:16:2
```

I have no idea why this would work for you but not for me.

**Comment by badaix** [comment] 2016-09-14 10:20
What OS are you using?
I'm facing the same issue on Mac OS X, but not on Raspbian Jessie.
Mac OS X also insists in having a `=` after the long option.

**Comment by maweki** [comment] 2016-09-14 10:39
Fedora 23 and 24. And I think this is a problem with all long form command line arguments. So it might be an issue with popl proper.

```
$ ./snapserver --streamBuffer 50
Settings file: /home/maweki/.config/snapcast/server.json
2016-09-14 12-35-39 [out] Adding service 'Snapcast'
2016-09-14 12-35-39 [out] PcmStream sampleFormat: 48000:16:2
2016-09-14 12-35-39 [out] PipeStream mode: create
2016-09-14 12-35-39 [out] Stream: {"fragment":"","host":"","path":"/tmp/snapfifo","query":{"buffer_ms":"20","codec":"flac","mode":"","name":"default","sampleformat":"48000:16:2"},"raw":"pipe:///tmp/snapfifo?name=default","scheme":"pipe"}
```

Still a buffer of 20ms

```
$ ./snapserver --help
Settings file: /home/maweki/.config/snapcast/server.json
2016-09-14 12-36-03 [out] Adding service 'Snapcast'
2016-09-14 12-36-03 [out] PcmStream sampleFormat: 48000:16:2
2016-09-14 12-36-03 [out] PipeStream mode: create
```

Starts the server and not the help

`$ ./snapserver --daemon 20` fails to parse (help is shown). `$ ./snapserver --daemon=20` doesn't start the snapserver as a daemon but starts normally. `$ ./snapserver -d 20` works as expected.

**Comment by maweki** [comment] 2016-09-14 10:45
```
$ ./popl --string "foo"
NonOptionArg: foo
UnknownOptions: --string
floatOption  - isSet: 0, value: 1.23, reference: 1.23
doubleOption - isSet: 0, value: 3.14159
terminate called after throwing an instance of 'std::out_of_range'
  what():  option not set: "-s"
Aborted (Speicherabzug geschrieben)
```

**Comment by badaix** [comment] 2016-09-17 08:24
Should be fixed now. Can you please try the latest version?

**Closed** 2016-11-10 09:08 UTC
