### ISSUE TITLE
Stuttering in sound

### ISSUE THREAD

**Issue by WallyDW** [badaix/snapcast#937] opened 2021-11-08 17:14 UTC
I am trying to make a smart speaker just like a Sonos, with SnapCast as the music system and Rhasspy as the smart assistant system.
I have a dedicated server for the SnapServer (v0.25.0 (rev 2af5292f)) and also a dedicated server for Rhasspy to handle all the smart assistant features that can be offloaded to this system.
The smart speaker is just running 2 things, SnapClient (Version 0.25.0, revision 2af5292f) and Rhasspy with wakeword/Audio commands and Text to Speak features.

The dedicated SnapCast server, called Jukebox, is an Intel Core i7-6820HQ CPU with 24Gb ram and a SSD for storage, where the media files are also located. This is running on a 64bit Debian Bullseye Linux with Mopidy as a feeder to the SnapServer. Snapserver is installed from the .deb package.

The smart speaker, called RhasspySat, is a Raspberry Pi 4B, 4Gb with a Seeed Respeaker 4-Mic Linear Array Kit Audio Hat (https://wiki.seeedstudio.com/ReSpeaker_4-Mic_Linear_Array_Kit_for_Raspberry_Pi/) used both for recording and playing. This on is running the 32bit Raspberry OS based on Buster. Snapclient is installed from the .deb package.

SnapClient seems to playing fine on the Rhasspy if I use a direct hardware device, like ac108.
It still have a few lines in the syslog now and then, but it does not affect the sound at all.
The problem is I need to use the dmixer instead to allow Rhasspy access to the speaker too and that output device causes a lot of stuttering in the sound.
Shutting down the Rhasspy Client does not affect the stuttering.

What I noticed is that the Snapclient is increasing the period and buffer size from the default, which does not occur when I use the ac108 directly.
I have provided what info I thought might be useful in solving this. If anything else is needed then please ask and I hope you can then help me solve it.

Jukebox Snapserver.conf:
```
[server]
threads = -1
pidfile = /var/run/snapserver/pid

[http]
enabled = true
bind_to_address = 0.0.0.0
port = 1780

[tcp]
enabled = true
bind_to_address = 0.0.0.0
port = 1705

[stream]
bind_to_address = 0.0.0.0
port = 1704
source = pipe:///tmp/snapfifo?name=default
sampleformat = 48000:16:2
codec = pcm
chunk_ms = 20
buffer = 2000
send_to_muted = false

[logging]
sink = system
filter = *:info
```

Rhasspy /etc/asound.conf:
```
defaults.pcm.rate_converter "samplerate_best"

pcm.!default {
    type asym
    playback.pcm "dmixer"
    capture.pcm "ac108"
}

pcm.ac108 {
    type plug
    slave {
        rate 48000
        format S32_LE
        pcm "hw:seeed8micvoicec"
    }
}

pcm.dmixer {
    type plug
    slave {
        pcm {
            type dmix
            ipc_key 555555
            ipc_perm 0666
            slave {
                pcm "hw:seeed8micvoicec"
                format S32_LE
                channels 8
            }
            bindings {
                0 0
                1 1
                2 2
                3 3
                4 4
                5 5
                6 6
                7 7
            }
        }
        channels 8
        format S32_LE
        rate 48000
    }
    ttable.0.0 1
    ttable.1.1 1
    ttable.0.2 1
    ttable.1.3 1
    ttable.0.4 1
    ttable.1.5 1
    ttable.0.6 1
    ttable.1.7 1
}

pcm.ac101 {
    type plug
    slave {
        pcm "hw:seeed8micvoicec"
        channels 8
        format S32_LE
        rate 16000
    }
    ttable.0.0 1
    ttable.1.1 1
    ttable.0.2 1
    ttable.1.3 1
    ttable.0.4 1
    ttable.1.5 1
    ttable.0.6 1
    ttable.1.7 1
}
```

RhasspySat Snapclient OPTS:
`"-h 10.10.12.70 -p 1704 -s 5 --player alsa --logsink system -e --logfilter *:debug"`

RhasspySat> device list
```
0: null
Discard all samples (playback) or generate zero samples (capture)

1: jack
JACK Audio Connection Kit

2: pulse
PulseAudio Sound Server

3: default

4: ac108

5: dmixer

6: ac101

7: sysdefault:CARD=Headphones
bcm2835 Headphones, bcm2835 Headphones
Default Audio Device

8: dmix:CARD=Headphones,DEV=0
bcm2835 Headphones, bcm2835 Headphones
Direct sample mixing device

9: dsnoop:CARD=Headphones,DEV=0
bcm2835 Headphones, bcm2835 Headphones
Direct sample snooping device

10: hw:CARD=Headphones,DEV=0
bcm2835 Headphones, bcm2835 Headphones
Direct hardware device without any conversions

11: plughw:CARD=Headphones,DEV=0
bcm2835 Headphones, bcm2835 Headphones
Hardware device with all software conversions

12: usbstream:CARD=Headphones
bcm2835 Headphones
USB Stream Output

13: sysdefault:CARD=seeed8micvoicec
seeed-8mic-voicecard, bcm2835-i2s-ac10x-codec0 ac10x-codec0-0
Default Audio Device

14: dmix:CARD=seeed8micvoicec,DEV=0
seeed-8mic-voicecard, bcm2835-i2s-ac10x-codec0 ac10x-codec0-0
Direct sample mixing device

15: dsnoop:CARD=seeed8micvoicec,DEV=0
seeed-8mic-voicecard, bcm2835-i2s-ac10x-codec0 ac10x-codec0-0
Direct sample snooping device

16: hw:CARD=seeed8micvoicec,DEV=0
seeed-8mic-voicecard, bcm2835-i2s-ac10x-codec0 ac10x-codec0-0
Direct hardware device without any conversions

17: plughw:CARD=seeed8micvoicec,DEV=0
seeed-8mic-voicecard, bcm2835-i2s-ac10x-codec0 ac10x-codec0-0
Hardware device with all software conversions

18: usbstream:CARD=seeed8micvoicec
seeed-8mic-voicecard
USB Stream Output
```

RhasspySat> Syslog:
```
Nov  8 09:13:23 rhasspysat1 systemd[1]: Started Snapcast client.
Nov  8 09:13:23 rhasspysat1 snapclient[1802]: Trying to get PCM device for player: alsa, parameter: , card: 5
Nov  8 09:13:23 rhasspysat1 snapclient[1802]: Version 0.25.0, revision 2af5292f
Nov  8 09:13:23 rhasspysat1 snapclient[1802]: Resolving host IP for: 10.10.12.70
Nov  8 09:13:23 rhasspysat1 snapclient[1802]: Connecting
Nov  8 09:13:23 rhasspysat1 snapclient[1802]: Connected to 10.10.12.70
Nov  8 09:13:23 rhasspysat1 snapclient[1802]: My MAC: "dc:a6:32:3f:c4:5e", socket: 9
Nov  8 09:13:23 rhasspysat1 snapclient[1802]: outstanding async_write
Nov  8 09:13:23 rhasspysat1 snapclient[1802]: ServerSettings - buffer: 2000, latency: 0, volume: 100, muted: 0
Nov  8 09:13:23 rhasspysat1 snapclient[1802]: metadata:{"STREAM":"default"}
Nov  8 09:13:23 rhasspysat1 snapclient[1802]: Codec: pcm, sampleformat: 48000:16:2
Nov  8 09:13:23 rhasspysat1 snapclient[1802]: Player name: alsa, device: dmixer, description: <none>, idx: 5, sharing mode: unspecified, parameters: <none>
Nov  8 09:13:23 rhasspysat1 snapclient[1802]: Mixer mode: software, parameters: <none>
Nov  8 09:13:23 rhasspysat1 snapclient[1802]: Sampleformat: 48000:16:2, stream: 48000:16:2
Nov  8 09:13:23 rhasspysat1 snapclient[1802]: Using default buffer_time: 80 ms, default fragments: 4
Nov  8 09:13:23 rhasspysat1 snapclient[1802]: ACCESS:  MMAP_INTERLEAVED MMAP_NONINTERLEAVED MMAP_COMPLEX RW_INTERLEAVED RW_NONINTERLEAVED
Nov  8 09:13:23 rhasspysat1 snapclient[1802]: FORMAT:  S8 U8 S16_LE S16_BE U16_LE U16_BE S24_LE S24_BE U24_LE U24_BE S32_LE S32_BE U32_LE U32_BE FLOAT_LE FLOAT_BE FLOAT64_LE FLOAT64_BE MU_LAW A_LAW IMA_ADPCM S20_LE S20_BE U20_LE U20_BE S24_3LE S24_3BE U24_3LE U24_3BE S20_3LE S20_3BE U20_3LE U20_3BE S18_3LE S18_3BE U18_3LE U18_3BE
Nov  8 09:13:23 rhasspysat1 snapclient[1802]: SUBFORMAT:  STD
Nov  8 09:13:23 rhasspysat1 snapclient[1802]: SAMPLE_BITS: [4 64]
Nov  8 09:13:23 rhasspysat1 snapclient[1802]: FRAME_BITS: [4 640000]
Nov  8 09:13:23 rhasspysat1 snapclient[1802]: CHANNELS: [1 10000]
Nov  8 09:13:23 rhasspysat1 snapclient[1802]: RATE: [4000 4294967295)
Nov  8 09:13:23 rhasspysat1 snapclient[1802]: PERIOD_TIME: 125000
Nov  8 09:13:23 rhasspysat1 snapclient[1802]: PERIOD_SIZE: [500 536870912)
Nov  8 09:13:23 rhasspysat1 snapclient[1802]: PERIOD_BYTES: [250 4294967295)
Nov  8 09:13:23 rhasspysat1 snapclient[1802]: PERIODS: (0 2147484)
Nov  8 09:13:23 rhasspysat1 snapclient[1802]: BUFFER_TIME: [1 4294967295]
Nov  8 09:13:23 rhasspysat1 snapclient[1802]: BUFFER_SIZE: [1000 1073741823]
Nov  8 09:13:23 rhasspysat1 snapclient[1802]: BUFFER_BYTES: [500 4294967295]
Nov  8 09:13:23 rhasspysat1 snapclient[1802]: TICK_TIME: ALL
Nov  8 09:13:23 rhasspysat1 snapclient[1802]: Period time too small, changing from 20000 to 125000
Nov  8 09:13:23 rhasspysat1 snapclient[1802]: Buffer time smaller than 3 * periods: 80000 us < 375000 us, raising buffer time
Nov  8 09:13:23 rhasspysat1 snapclient[1802]: PCM name: dmixer, sample rate: 48000 Hz, channels: 2, buffer time: 250000 us, periods: 2, period time: 125000 us, period frames: 6000
Nov  8 09:13:23 rhasspysat1 snapclient[1802]: setVolume exp with base 10: 1 => 1
Nov  8 09:13:23 rhasspysat1 snapclient[1802]: Resizing buffer from 0 to 48000
Nov  8 09:13:23 rhasspysat1 snapclient[1802]: No chunks available
Nov  8 09:13:23 rhasspysat1 snapclient[1802]: Failed to get chunk
Nov  8 09:13:24 rhasspysat1 snapclient[1802]: diff to server [ms]: 2.97706e+08
Nov  8 09:13:24 rhasspysat1 snapclient[1802]: snd_pcm_avail_delay failed: Broken pipe (-32), avail: 12000, delay: 0, using snd_pcm_avail amd snd_pcm_delay.
Nov  8 09:13:24 rhasspysat1 snapclient[1802]: snd_pcm_delay failed: Broken pipe (-32), avail: -32, delay: 0
Nov  8 09:13:24 rhasspysat1 snapclient[1802]: snd_pcm_avail_delay failed: Broken pipe (-32), avail: 11946, delay: 53, using snd_pcm_avail amd snd_pcm_delay.
Nov  8 09:13:24 rhasspysat1 snapclient[1802]: snd_pcm_delay failed: Broken pipe (-32), avail: -32, delay: 53
Nov  8 09:13:25 rhasspysat1 snapclient[1802]: snd_pcm_avail_delay failed: Broken pipe (-32), avail: 11944, delay: 56, using snd_pcm_avail amd snd_pcm_delay.
Nov  8 09:13:25 rhasspysat1 snapclient[1802]: snd_pcm_delay failed: Broken pipe (-32), avail: -32, delay: 56
Nov  8 09:13:25 rhasspysat1 snapclient[1802]: Silent frames: 6707, frames: 12000, age: -139.741
Nov  8 09:13:25 rhasspysat1 snapclient[1802]: Chunk: 32#01132#01132#01132#0111#01114#0110
Nov  8 09:13:26 rhasspysat1 snapclient[1802]: Chunk: 32#01132#01132#01132#0112#0110#0110
Nov  8 09:13:26 rhasspysat1 snapclient[1802]: snd_pcm_avail_delay failed: Broken pipe (-32), avail: 11988, delay: 11, using snd_pcm_avail amd snd_pcm_delay.
Nov  8 09:13:26 rhasspysat1 snapclient[1802]: snd_pcm_delay failed: Broken pipe (-32), avail: -32, delay: 11
Nov  8 09:13:27 rhasspysat1 snapclient[1802]: Chunk: 161#01132#01132#01132#0116#0116#0110
Nov  8 09:13:27 rhasspysat1 snapclient[1802]: snd_pcm_avail_delay failed: Broken pipe (-32), avail: 11861, delay: 139, using snd_pcm_avail amd snd_pcm_delay.
Nov  8 09:13:27 rhasspysat1 snapclient[1802]: snd_pcm_delay failed: Broken pipe (-32), avail: -32, delay: 139
Nov  8 09:13:28 rhasspysat1 snapclient[1802]: Chunk: 308#011161#011161#011161#01110#01110#0110
Nov  8 09:13:28 rhasspysat1 snapclient[1802]: XRUN while writing to PCM: Broken pipe
Nov  8 09:13:29 rhasspysat1 snapclient[1802]: Chunk: -2144#011146#011146#011146#01115#0110#0110
Nov  8 09:13:29 rhasspysat1 snapclient[1802]: XRUN while writing to PCM: Broken pipe
Nov  8 09:13:30 rhasspysat1 snapclient[1802]: snd_pcm_avail_delay failed: Broken pipe (-32), avail: 11975, delay: 24, using snd_pcm_avail amd snd_pcm_delay.
Nov  8 09:13:30 rhasspysat1 snapclient[1802]: snd_pcm_delay failed: Broken pipe (-32), avail: -32, delay: 24
Nov  8 09:13:30 rhasspysat1 snapclient[1802]: Chunk: -4463#01132#01132#01132#01120#0110#0110
Nov  8 09:13:31 rhasspysat1 snapclient[1802]: pMiniBuffer->full() && (abs(pMiniBuffer->mean()) > 50): -214393
Nov  8 09:13:31 rhasspysat1 snapclient[1802]: Chunk: -4430#011-2144#01132#01132#01124#0111#0110
Nov  8 09:13:31 rhasspysat1 snapclient[1802]: Silent frames: 9272, frames: 11997, age: -193.178
Nov  8 09:13:31 rhasspysat1 snapclient[1802]: XRUN while writing to PCM: Broken pipe
Nov  8 09:13:31 rhasspysat1 snapclient[1802]: snd_pcm_avail_delay failed: Broken pipe (-32), avail: 12000, delay: 0, using snd_pcm_avail amd snd_pcm_delay.
Nov  8 09:13:31 rhasspysat1 snapclient[1802]: snd_pcm_delay failed: Broken pipe (-32), avail: -32, delay: 0
Nov  8 09:13:32 rhasspysat1 snapclient[1802]: Chunk: -2325#011-2342#011-2342#011-2342#0113#01116#0110
Nov  8 09:13:32 rhasspysat1 snapclient[1802]: snd_pcm_avail_delay failed: Broken pipe (-32), avail: 11942, delay: 57, using snd_pcm_avail amd snd_pcm_delay.
Nov  8 09:13:32 rhasspysat1 snapclient[1802]: snd_pcm_delay failed: Broken pipe (-32), avail: -32, delay: 57
Nov  8 09:13:33 rhasspysat1 snapclient[1802]: Chunk: -2131#011-2325#011-2325#011-2325#0117#0111#0110
Nov  8 09:13:33 rhasspysat1 snapclient[1802]: snd_pcm_avail_delay failed: Broken pipe (-32), avail: 11938, delay: 61, using snd_pcm_avail amd snd_pcm_delay.
Nov  8 09:13:33 rhasspysat1 snapclient[1802]: snd_pcm_delay failed: Broken pipe (-32), avail: -32, delay: 61
Nov  8 09:13:34 rhasspysat1 snapclient[1802]: snd_pcm_avail_delay failed: Broken pipe (-32), avail: 11915, delay: 85, using snd_pcm_avail amd snd_pcm_delay.
Nov  8 09:13:34 rhasspysat1 snapclient[1802]: snd_pcm_delay failed: Broken pipe (-32), avail: -32, delay: 85
Nov  8 09:13:34 rhasspysat1 snapclient[1802]: Chunk: -1813#011-2131#011-2131#011-2131#01111#0110#0110
Nov  8 09:13:35 rhasspysat1 snapclient[1802]: Chunk: -1776#011-2017#011-2017#011-2017#01115#0110#0110
Nov  8 09:13:35 rhasspysat1 snapclient[1802]: XRUN while writing to PCM: Broken pipe
Nov  8 09:13:35 rhasspysat1 snapclient[1802]: snd_pcm_avail_delay failed: Broken pipe (-32), avail: 12000, delay: 0, using snd_pcm_avail amd snd_pcm_delay.
Nov  8 09:13:35 rhasspysat1 snapclient[1802]: snd_pcm_delay failed: Broken pipe (-32), avail: -32, delay: 0
Nov  8 09:13:35 rhasspysat1 snapclient[1802]: snd_pcm_avail_delay failed: Broken pipe (-32), avail: 11191, delay: 808, using snd_pcm_avail amd snd_pcm_delay.
Nov  8 09:13:35 rhasspysat1 snapclient[1802]: snd_pcm_delay failed: Broken pipe (-32), avail: -32, delay: 808
Nov  8 09:13:36 rhasspysat1 snapclient[1802]: Chunk: -3941#011-2131#011-2131#011-2131#01120#01114#0110
Nov  8 09:13:36 rhasspysat1 snapclient[1802]: pMiniBuffer->full() && (abs(pMiniBuffer->mean()) > 50): -213121
Nov  8 09:13:36 rhasspysat1 snapclient[1802]: snd_pcm_avail_delay failed: Broken pipe (-32), avail: 11944, delay: 56, using snd_pcm_avail amd snd_pcm_delay.
Nov  8 09:13:36 rhasspysat1 snapclient[1802]: snd_pcm_delay failed: Broken pipe (-32), avail: -32, delay: 56
Nov  8 09:13:36 rhasspysat1 snapclient[1802]: Silent frames: 6193, frames: 11335, age: -129.026
Nov  8 09:13:37 rhasspysat1 snapclient[1802]: snd_pcm_avail_delay failed: Broken pipe (-32), avail: 11335, delay: 664, using snd_pcm_avail amd snd_pcm_delay.
Nov  8 09:13:37 rhasspysat1 snapclient[1802]: snd_pcm_delay failed: Broken pipe (-32), avail: -32, delay: 664
Nov  8 09:13:37 rhasspysat1 snapclient[1802]: Chunk: 122#011122#011122#011122#0111#0110#0110
Nov  8 09:13:37 rhasspysat1 snapclient[1802]: snd_pcm_avail_delay failed: Broken pipe (-32), avail: 11226, delay: 774, using snd_pcm_avail amd snd_pcm_delay.
Nov  8 09:13:37 rhasspysat1 snapclient[1802]: snd_pcm_delay failed: Broken pipe (-32), avail: -32, delay: 774
Nov  8 09:13:38 rhasspysat1 snapclient[1802]: Chunk: 356#011315#011315#011315#0115#0111#0110
Nov  8 09:13:38 rhasspysat1 snapclient[1802]: XRUN while writing to PCM: Broken pipe
```

**Comment by WallyDW** [comment] 2021-11-09 09:47
Can this be the cause?
https://github.com/alsa-project/alsa-lib/issues/131

**Comment by badaix** [comment] 2021-12-28 10:44
Looks like the `dmix` device is not capable of reporting it's own playback latency:

```
Nov  8 09:13:24 rhasspysat1 snapclient[1802]: snd_pcm_avail_delay failed: Broken pipe (-32), avail: 12000, delay: 0, using snd_pcm_avail amd snd_pcm_delay.
```

Since this is not a bug, and no one here seems to know a solution or workaround, I will close this. Maybe you can open a [discussion](https://github.com/badaix/snapcast/discussions) for this.

**Closed by badaix** 2021-12-28 10:44 UTC
