### ISSUE TITLE
Blocking shutdown if no network connection present

### ISSUE THREAD

**Issue by PhoGGy** [badaix/snapcast#223] opened 2017-03-30 07:36 UTC
Hey badaix!
I found another small issue in the startup of snapcast.
If there´s no network interface present, the snapcast client does say via `systemctl status` every second: 
`Exception in Controller::worker(): connect: Network is unreachable`
That should be right, I think.
But when I want to shutdown this machine, the snapclient does not respond to the stop command and has to be killed after the 90sec timeout by systemctl.
Maybe you can have a look at the code and find out what could be the issue?
Thanks! And Thanks for being this active on developing snapcast. It´s a great piece of software, especially combined with librespot!
**EDIT:**
I have to correct that a little bit.
I´m using `ifdown` and `ifup` to switch between WLAN client and WLAN AP Mode. The config for that is in the `/etc/network/interfaces`.
At startup (of snapclient) no wlan interface is present. Afterwards I´m running `ifup` to connect to a wlan network or spawn an Access Point. Snapclient is doing great with detecting that and connecting to a snapserver if there is one.
But If I restart debian, the snapclient service does block sometimes the reboot. I couldn´t reproduce when it is blocking for full 90sec and when it is blocking for just a few seconds.
I was able to reproduce one block scenario: If I´m running ifup and try to connect to a nonexistent wifi network and want to reboot afterwards, it does block forever (90sec).
I´ll try to investigate it further.
I hope I could explain the issue as good as possible in english. If you want to get more information, you could contact me in german as well.

**Comment by badaix** [comment] 2020-05-13 08:44
I observed this also from time to time, and tried to reproduce it now (while I was doing some refactoring on the client), but I didn't succeed to reproduce it (even with a pre-refactored version running in parallel). 
For me it was also related to switching off the WiFi or disconnecting the LAN cable (i.e. a sudden, non-graceful TCP disconnect). 
I will do some more tests, maybe it got fixed in the meantime. I will close this ticket if I'm still not able to reproduce it. 
Could you try it again with a recent version (if you're still interested)?

**Comment by PhoGGy** [comment] 2020-05-19 09:05
Thanks for the comment. I'm not using snap cast at the moment, so I don't know when I'd reproduce it.
Keep up the great work! :)

**Closed** 2020-06-13 16:08 UTC
